site_name: Unlearn Diff
docs_dir: docs  
site_dir: docs_build  

nav:
  - Home: README.md
  - Algorithms:
    - Concept Ablation: 
      - Usage: algorithms/concept_ablation.md
      # - Examples: examples/concept_ablation.md
      # - Configs: configs/concept_ablation.md
    - Erase Diff: 
      - Usage: algorithms/erase_diff.md 
      - Examples: examples/erase_diff.md
      - Configs: configs/erase_diff.md

    - ESD: 
      - Usage: algorithms/esd.md
      - Examples: examples/esd.md
      - Configs: configs/esd.md
      
    - Forget Me Not: 
      - Usage: algorithms/forget_me_not.md
      - Examples: examples/forget_me_not.md
      - Configs: configs/forget_me_not.md

    - Saliency Unlearning: 
      - Usage: algorithms/saliency.md
      - Examples: examples/saliency.md
      - Configs: configs/saliency.md
    - Scissor Hands: 
      - Usage: algorithms/scissorhands.md
      - Examples: examples/scissorhands.md
      - Configs: configs/scissorhands.md
    - Selective Amnesia: 
      - Usage: algorithms/selective_amnesia.md
    #   - Examples: examples/selective_amnesia.md
    #   - Configs: configs/selective_amnesia.md
    - Semi Permeable Membrane: 
      - Usage: algorithms/semipermeable_membrane.md
      - Examples: examples/semipermeable_membrane.md
      - Configs: configs/semipermeable_membrane.md
    - Unified Concept Editing: 
      - Usage: algorithms/uce.md
      - Examples: examples/uce.md
      - Configs: configs/uce.md
  - Contributing: algorithms/contributing.md
theme:
  name: readthedocs  