site_name: Unlearn Diff
docs_dir: docs  
site_dir: docs_build  

nav:
  - Home: README.md
  - Algorithms:
    - Concept Ablation: algorithms/concept_ablation.md
    - Erase Diff: 
      - Usage: algorithms/erase_diff.md 
      - Examples: examples/erase_diff.md
      - Configs: configs/erase_diff.md

    - ESD: 
      - Usage: algorithms/esd.md
      - Examples: examples/esd.md
      - Configs: configs/esd.md
      
    - Forget Me Not: 
      - Usage: algorithms/forget_me_not.md
      - Examples: examples/forget_me_not.md
      - Configs: configs/forget_me_not.md

    - Saliency Unlearning: algorithms/saliency.md
    - Scissor Hands: algorithms/scissorhands.md
    - Selective Amnesia: 
      - Usage: algorithms/selective_amnesia.md
      - Examples: examples/selective_amnesia.md
      - Configs: configs/selective_amnesia.md
    - Semi Permeable Membrane: algorithms/semi_permeable.md
    - Unified Concept Editing: algorithms/uce.md
  - Contributing: algorithms/contributing.md
theme:
  name: readthedocs  