site_name: Unlearn Diff
docs_dir: docs  
site_dir: docs_build  

nav:
  - Usage:
    - Installation: usage/installation.md
    - How to use existing unlearning algorithms: usage/unlearn_algorithm_usage.md
    - How to evaluate: usage/how_to_evaluate.md
    
  - Unlearn Algorithms:
    - Concept Ablation: 
      - Usage: unlearn/algorithms/concept_ablation.md
      - Examples: unlearn/examples/concept_ablation.md
      - Configs: unlearn/configs/concept_ablation.md

    - Erase Diff: 
      - Usage: unlearn/algorithms/erase_diff.md 
      - Examples: unlearn/examples/erase_diff.md
      - Configs: unlearn/configs/erase_diff.md

    - ESD: 
      - Usage: unlearn/algorithms/esd.md
      - Examples: unlearn/examples/esd.md
      - Configs: unlearn/configs/esd.md
      
    - Forget Me Not: 
      - Usage: unlearn/algorithms/forget_me_not.md
      - Examples: unlearn/examples/forget_me_not.md
      - Configs: unlearn/configs/forget_me_not.md

    - Saliency Unlearning: 
      - Usage: unlearn/algorithms/saliency.md
      - Examples: unlearn/examples/saliency.md
      - Configs: unlearn/configs/saliency.md

    - Scissor Hands: 
      - Usage: unlearn/algorithms/scissorhands.md
      - Examples: unlearn/examples/scissorhands.md
      - Configs: unlearn/configs/scissorhands.md

    - Selective Amnesia: 
      - Usage: unlearn/algorithms/selective_amnesia.md
      - Examples: unlearn/examples/selective_amnesia.md
      - Configs: unlearn/configs/selective_amnesia.md

    - Semi Permeable Membrane: 
      - Usage: unlearn/algorithms/semipermeable_membrane.md
      - Examples: unlearn/examples/semipermeable_membrane.md
      - Configs: unlearn/configs/semipermeable_membrane.md

    - Unified Concept Editing: 
      - Usage: unlearn/algorithms/uce.md
      - Examples: unlearn/examples/uce.md
      - Configs: unlearn/configs/uce.md

    - Adv Unlearn:
      - Usage: unlearn/mu_defense/adv_unlearn.md
      - Config: unlearn/mu_defense/config.md

  - Evaluation: 
    - Non-Attack evalaution: 
      - No attack: 
        - Usage: mu_attack/attack/no_attack.md
        - Config: mu_attack/configs/no_attack.md

    - Robustness Eval UnlearnDiffAtk:
      - Hard Prompt: 
        - Usage: mu_attack/attack/hard_prompt.md
        - Config: mu_attack/configs/hard_prompt.md

      - Random:
        - Usage: mu_attack/attack/random.md
        - Config: mu_attack/configs/random.md

      - Seed Search:
        - Usage: mu_attack/attack/seed_search.md
        - Config: mu_attack/configs/seed_search.md

      - Text Grad:
        - Usage: mu_attack/attack/text_grad.md
        - Config: mu_attack/configs/text_grad.md
  
    - Utility Eval:
      - Concept Ablation:
        - Usage: evaluation/concept_ablation.md
      - Erase Diff: 
        - Usage: evaluation/erase_diff.md
      - ESD: 
        - Usage: evaluation/esd.md
      - Forget Me Not: 
        - Usage: evaluation/forget_me_not.md
      - Saliency Unlearning: 
        - Usage: evaluation/saliency.md
      - Scissor Hands: 
        - Usage: evaluation/scissorhands.md
      - Semi Permeable Membrane: 
        - Usage: evaluation/semipermeable_membrane.md
      - Unified Concept Editing: 
        - Usage: evaluation/uce.md
      - MU_Defense:
        - Usage: evaluation/adv_unlearn_evaluation.md

theme:
  name: readthedocs  