site_name: Unlearn Diff
docs_dir: docs  
site_dir: docs_build  

nav:
  - Unlearn: unlearn/README.md
  - Attack: attack/Readme_MU_Attack.md 
  - Unlearn Algorithms:
    - Concept Ablation: 
      - Usage: unlearn/algorithms/concept_ablation.md
      # - Examples: examples/concept_ablation.md
      # - Configs: configs/concept_ablation.md
    - Erase Diff: 
      - Usage: unlearn/algorithms/erase_diff.md 
      - Examples: unlearn/examples/erase_diff.md
      - Configs: unlearn/configs/erase_diff.md
      - Evaluation: evaluation/erase_diff.md

    - ESD: 
      - Usage: unlearn/algorithms/esd.md
      - Examples: unlearn/examples/esd.md
      - Configs: unlearn/configs/esd.md
      - Evaluation: evaluation/esd.md
      
    - Forget Me Not: 
      - Usage: unlearn/algorithms/forget_me_not.md
      - Examples: unlearn/examples/forget_me_not.md
      - Configs: unlearn/configs/forget_me_not.md
      - Evaluation: evaluation/forget_me_not.md

    - Saliency Unlearning: 
      - Usage: unlearn/algorithms/saliency.md
      - Examples: unlearn/examples/saliency.md
      - Configs: unlearn/configs/saliency.md
      - Evaluation: evaluation/saliency.md 

    - Scissor Hands: 
      - Usage: unlearn/algorithms/scissorhands.md
      - Examples: unlearn/examples/scissorhands.md
      - Configs: unlearn/configs/scissorhands.md
      - Evaluation: evaluation/scissorhands.md

    - Selective Amnesia: 
      - Usage: unlearn/algorithms/selective_amnesia.md
    #   - Examples: examples/selective_amnesia.md
    #   - Configs: configs/selective_amnesia.md
    - Semi Permeable Membrane: 
      - Usage: unlearn/algorithms/semipermeable_membrane.md
      - Examples: unlearn/examples/semipermeable_membrane.md
      - Configs: unlearn/configs/semipermeable_membrane.md
      - Evaluation: evaluation/semipermeable_membrane.md

    - Unified Concept Editing: 
      - Usage: unlearn/algorithms/uce.md
      - Examples: unlearn/examples/uce.md
      - Configs: unlearn/configs/uce.md
      - Evaluation: evaluation/uce.md

  - Unlearn Mu Attack: 
    - Hard Prompt: 
      - Usage: attack/algorithms/hard_prompt.md
      - Config: attack/configs/hard_prompt.md
      - Examples: attack/examples/hard_prompt.md
  
  - Evaluation :
    - Usage: evaluation/README.md

  - Contributing: algorithms/contributing.md
theme:
  name: readthedocs  