model_config: "configs/generate_sd.yaml"
ckpt_path: "../mu_erasing_concept_esd/results/style50/"
theme: "Abstractionism"
cfg_text: 9.0
seed: 188
ddim_steps: 100
image_height: 512
image_width: 512
ddim_eta: 0.0
output_dir: "output/eval_results/mu_results/esd/style50/"
eval_output_dir: "output/eval_results/mu_results/esd/"
original_image_dir: "data/evaluation_images/"
