precision: "fp32"
spm_multiplier: 1.0
v2: false
matching_metric: "clipcos_tokenuni"
model_config: "mu/algorithms/semipermeable_membrane/config"
base_model: "path to base model"
theme: "Abstractionism"
seed: 188
task: "class"
sampler_output_dir: "outputs/eval_results/mu_results/ca/"
seed_list: ["188"]
# classification_model: "vit_large_patch16_224.augreg_in21k"
classification_model: "vit_large_patch16_224"
classification_ckpt: "outputs/esd/finetuned_models/esd_Abstractionism_model.pth"
eval_output_dir: "outputs/eval_results/mu_results/esd/"
reference_dir: "/home/ubuntu/Projects/msu_unlearningalgorithm/data/quick-canvas-dataset/sample/"
forget_theme: "Abstractionism"
fid_output_path: "outputs/eval_results/mu_results/esd/"
multiprocessing: false