# semipermeable_membrane/config/train_config.yaml

pretrained_model:
  name_or_path: "CompVis/stable-diffusion-v1-4"
  v2: false
  v_pred: false
  clip_skip: 1

network:
  rank: 1
  alpha: 1.0

train:
  precision: float32
  noise_scheduler: "ddim"
  iterations: 3000
  batch_size: 1
  lr: 0.0001
  unet_lr: 0.0001
  text_encoder_lr: 5e-05
  optimizer_type: "AdamW8bit"
  lr_scheduler: "cosine_with_restarts"
  lr_warmup_steps: 500
  lr_scheduler_num_cycles: 3
  max_denoising_steps: 30

save:
  name: "Abstractionism"
  path: "output/Abstractionism"
  per_steps: 500
  precision: float32

other:
  use_xformers: true

wandb:
  project: "semipermeable_membrane_project"
  name: "spm_run"

# Additional configurations if needed

# semipermeable_membrane/configs/Abstractionism/prompt.yaml

prompt:
  target: "Abstractionism"
  positive: "Abstractionism"
  unconditional: ""
  neutral: ""
  action: "erase_with_la"
  guidance_scale: "1.0"
  resolution: 512
  batch_size: 1
  dynamic_resolution: true
  la_strength: 1000
  sampling_batch_size: 4

