model_config: "mu/algorithms/saliency_unlearning/configs/model_config.yaml"
ckpt_path: "outputs/saliency_unlearning/finetuned_models/saliency_unlearning_Abstractionism_model.pth"
theme: "Bricks"
cfg_text: 9.0
devices: "0"
seed: 188
task: "class"
ddim_steps: 100
image_height: 512
image_width: 512
ddim_eta: 0.0
sampler_output_dir: "outputs/eval_results/mu_results/saliency_unlearning/"
seed_list: ["188"]
# classification_model: "vit_large_patch16_224.augreg_in21k"
classification_model: "vit_large_patch16_224"
eval_output_dir: "outputs/eval_results/mu_results/saliency_unlearning/"
reference_dir: "/home/ubuntu/Projects/msu_unlearningalgorithm/data/quick-canvas-dataset/sample/"
forget_theme: "Bricks"
fid_output_path: "outputs/eval_results/mu_results/saliency_unlearning/"
multiprocessing: False