ckpt_path: "/home/ubuntu/Projects/UnlearnCanvas/UnlearnCanvas/machine_unlearning/models/diffuser/style50"

# Dataset directories
raw_dataset_dir: "/home/ubuntu/Projects/msu_unlearningalgorithm/data/quick-canvas-dataset/sample"
processed_dataset_dir: "/home/ubuntu/Projects/msu_unlearningalgorithm/mu/algorithms/forget_me_not/data"
dataset_type : "unlearncanvas"
template : "style"
template_name : "Abstractionism"
use_sample: True  # Use the sample dataset for training

use_ti : True 
ti_weights_path : "outputs/forget_me_not/ti_models/step_inv_500.safetensors"

# Training configuration
mixed_precision: "fp16"
gradient_accumulation_steps:  1
train_text_encoder: False
enable_xformers_memory_efficient_attention : False
gradient_checkpointing: False
allow_tf32 : False
scale_lr : False
train_batch_size : 1
use_8bit_adam : False
adam_beta1 : 0.9
adam_beta2 : 0.999
adam_weight_decay: 0.01
adam_epsilon: 1.0e-08
size : 512
with_prior_preservation : False
num_train_epochs : 1
lr_warmup_steps : 1 
lr_num_cycles : 1 
lr_power : 1.0
max-steps : 100
no_real_image : False
max_grad_norm : 1.0
checkpointing_steps : 500
set_grads_to_none : False
lr : 5e-5


# Output configurations
output_dir: "outputs/forget_me_not/finetuned_models/Abstractionism"  # Output directory to save results

# Device configuration
devices: "0"  # CUDA devices to train on (comma-separated)

only-xa : True 
