# Training parameters
train_method: "xattn"  # Choices: ["noxattn", "selfattn", "xattn", "full", "notime", "xlayer", "selflayer"]
alpha: 0.1  # Guidance of start image used to train
epochs: 1  # Number of epochs to train
K_steps: 2  # Number of K steps
lr: 5e-5  # Learning rate

# Model configuration
model_config_path: "configs/train_erase_diff.yaml"  # Config path for Stable Diffusion
ckpt_path: "path/to/checkpoint.ckpt"  # Checkpoint path for Stable Diffusion

# Dataset directories
raw_dataset_dir: "/home/ubuntu/Projects/msu_unlearningalgorithm/data/quick-canvas-dataset/sample/quick-canvas-benchmark"  # Directory containing the original dataset organized by themes and classes
processed_dataset_dir: "/home/ubuntu/Projects/msu_unlearningalgorithm/mu/algorithms/erase_diff/data"  # Directory where the new datasets will be saved
dataset_type : "unlearncanvas"
template : "style"
template_name : "Abstractionism"


# Output configurations
output_dir: "results"  # Output directory to save results
separator: null  # Separator if you want to train multiple words separately

# Sampling and image configurations
image_size: 512  # Image size used to train
interpolation: "bicubic"  # Choices: ["bilinear", "bicubic", "lanczos"]
ddim_steps: 50  # DDIM steps of inference used to train
ddim_eta: 0.0  # DDIM eta parameter

# Device configuration
devices: "0"  # CUDA devices to train on (comma-separated)

# Additional flags
use_sample: True  # Use the sample dataset for training
num_workers: 4  # Number of workers for data loading
pin_memory: true  # Pin memory for data loading


