# Training parameters
train_method: "xattn"  # choices: ["noxattn", "selfattn", "xattn", "full", "notime", "xlayer", "selflayer"]
alpha: 0.75  # Guidance of start image used to train
epochs: 1

# Model configuration
model_config_path: "/home/ubuntu/Projects/msu_unlearningalgorithm/mu/algorithms/scissorhands/configs/model_config.yaml"  # Config path for Stable Diffusion
ckpt_path: "/home/ubuntu/Projects/UnlearnCanvas/UnlearnCanvas/machine_unlearning/models/compvis/style50/compvis.ckpt"  # Checkpoint path for Stable Diffusion

# Dataset directories
raw_dataset_dir: "/home/ubuntu/Projects/msu_unlearningalgorithm/data/quick-canvas-dataset/sample"
processed_dataset_dir: "/home/ubuntu/Projects/msu_unlearningalgorithm/mu/algorithms/scissorhands/data"
dataset_type : "unlearncanvas"
template : "style"
template_name : "Abstractionism"

# Output configuration
output_dir: "outputs/scissorhands/finetuned_models"  # Output directory to save results

# Sampling and image configurations
sparsity: 0.90 # threshold for masks
project: false
memory_num: 1
prune_num: 1

# Device configuration
devices: "0,1"  # CUDA devices (comma-separated)

# Additional configurations
use_sample: true  # Use sample dataset for training